version: '3.8'
services:
  stats-server:
    build: ./stats
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
  ewm-service:
    build: ./server
    container_name: ewm_server
    ports:
      - "8080:8080"
    depends_on:
      - db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - STATS_SERVER_URL=http://stats-server:9090
  db:
    build: ./db
    container_name: ewm_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=ewm,ewm;stats,ewm
      - POSTGRES_PASSWORD=ewm
