server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm
    username: ewm
    password: ewm
logging:
  level:
    com.notbadcode: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    defaultModelsExpandDepth: -1
