server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats
    username: ewm
    password: ewm
logging:
  level:
    com.notbadcode: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: ewm
    password: ewm
